// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api.proto

package v1alpha

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"

	timestamp "github.com/golang/protobuf/ptypes/timestamp"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type LineItemType int32

const (
	LineItemType_UNSPECIFIED LineItemType = 0
	LineItemType_DEBIT       LineItemType = 1
	LineItemType_CREDIT      LineItemType = 2
)

var LineItemType_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "DEBIT",
	2: "CREDIT",
}

var LineItemType_value = map[string]int32{
	"UNSPECIFIED": 0,
	"DEBIT":       1,
	"CREDIT":      2,
}

func (x LineItemType) String() string {
	return proto.EnumName(LineItemType_name, int32(x))
}

func (LineItemType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

type LineItem struct {
	Datetime             *timestamp.Timestamp `protobuf:"bytes,1,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Payer                string               `protobuf:"bytes,2,opt,name=payer,proto3" json:"payer,omitempty"`
	Payee                string               `protobuf:"bytes,3,opt,name=payee,proto3" json:"payee,omitempty"`
	Type                 LineItemType         `protobuf:"varint,4,opt,name=type,proto3,enum=indeed.actuary.v1alpha.LineItemType" json:"type,omitempty"`
	Usage                uint64               `protobuf:"varint,5,opt,name=usage,proto3" json:"usage,omitempty"`
	Urn                  string               `protobuf:"bytes,6,opt,name=urn,proto3" json:"urn,omitempty"`
	Detail               map[string]uint64    `protobuf:"bytes,7,rep,name=detail,proto3" json:"detail,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Labels               map[string]string    `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LineItem) Reset()         { *m = LineItem{} }
func (m *LineItem) String() string { return proto.CompactTextString(m) }
func (*LineItem) ProtoMessage()    {}
func (*LineItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}
func (m *LineItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LineItem.Unmarshal(m, b)
}
func (m *LineItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LineItem.Marshal(b, m, deterministic)
}
func (m *LineItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LineItem.Merge(m, src)
}
func (m *LineItem) XXX_Size() int {
	return xxx_messageInfo_LineItem.Size(m)
}
func (m *LineItem) XXX_DiscardUnknown() {
	xxx_messageInfo_LineItem.DiscardUnknown(m)
}

var xxx_messageInfo_LineItem proto.InternalMessageInfo

func (m *LineItem) GetDatetime() *timestamp.Timestamp {
	if m != nil {
		return m.Datetime
	}
	return nil
}

func (m *LineItem) GetPayer() string {
	if m != nil {
		return m.Payer
	}
	return ""
}

func (m *LineItem) GetPayee() string {
	if m != nil {
		return m.Payee
	}
	return ""
}

func (m *LineItem) GetType() LineItemType {
	if m != nil {
		return m.Type
	}
	return LineItemType_UNSPECIFIED
}

func (m *LineItem) GetUsage() uint64 {
	if m != nil {
		return m.Usage
	}
	return 0
}

func (m *LineItem) GetUrn() string {
	if m != nil {
		return m.Urn
	}
	return ""
}

func (m *LineItem) GetDetail() map[string]uint64 {
	if m != nil {
		return m.Detail
	}
	return nil
}

func (m *LineItem) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type Allocation struct {
	Datetime             *timestamp.Timestamp `protobuf:"bytes,1,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Who                  string               `protobuf:"bytes,2,opt,name=who,proto3" json:"who,omitempty"`
	What                 string               `protobuf:"bytes,3,opt,name=what,proto3" json:"what,omitempty"`
	Detail               map[string]uint64    `protobuf:"bytes,4,rep,name=detail,proto3" json:"detail,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Labels               map[string]string    `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Allocation) Reset()         { *m = Allocation{} }
func (m *Allocation) String() string { return proto.CompactTextString(m) }
func (*Allocation) ProtoMessage()    {}
func (*Allocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}
func (m *Allocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Allocation.Unmarshal(m, b)
}
func (m *Allocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Allocation.Marshal(b, m, deterministic)
}
func (m *Allocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Allocation.Merge(m, src)
}
func (m *Allocation) XXX_Size() int {
	return xxx_messageInfo_Allocation.Size(m)
}
func (m *Allocation) XXX_DiscardUnknown() {
	xxx_messageInfo_Allocation.DiscardUnknown(m)
}

var xxx_messageInfo_Allocation proto.InternalMessageInfo

func (m *Allocation) GetDatetime() *timestamp.Timestamp {
	if m != nil {
		return m.Datetime
	}
	return nil
}

func (m *Allocation) GetWho() string {
	if m != nil {
		return m.Who
	}
	return ""
}

func (m *Allocation) GetWhat() string {
	if m != nil {
		return m.What
	}
	return ""
}

func (m *Allocation) GetDetail() map[string]uint64 {
	if m != nil {
		return m.Detail
	}
	return nil
}

func (m *Allocation) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type RecordRequest struct {
	Available            map[string]uint64 `protobuf:"bytes,1,rep,name=available,proto3" json:"available,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Allocations          []*Allocation     `protobuf:"bytes,2,rep,name=allocations,proto3" json:"allocations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RecordRequest) Reset()         { *m = RecordRequest{} }
func (m *RecordRequest) String() string { return proto.CompactTextString(m) }
func (*RecordRequest) ProtoMessage()    {}
func (*RecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}
func (m *RecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordRequest.Unmarshal(m, b)
}
func (m *RecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordRequest.Marshal(b, m, deterministic)
}
func (m *RecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordRequest.Merge(m, src)
}
func (m *RecordRequest) XXX_Size() int {
	return xxx_messageInfo_RecordRequest.Size(m)
}
func (m *RecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RecordRequest proto.InternalMessageInfo

func (m *RecordRequest) GetAvailable() map[string]uint64 {
	if m != nil {
		return m.Available
	}
	return nil
}

func (m *RecordRequest) GetAllocations() []*Allocation {
	if m != nil {
		return m.Allocations
	}
	return nil
}

type RecordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordResponse) Reset()         { *m = RecordResponse{} }
func (m *RecordResponse) String() string { return proto.CompactTextString(m) }
func (*RecordResponse) ProtoMessage()    {}
func (*RecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}
func (m *RecordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordResponse.Unmarshal(m, b)
}
func (m *RecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordResponse.Marshal(b, m, deterministic)
}
func (m *RecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordResponse.Merge(m, src)
}
func (m *RecordResponse) XXX_Size() int {
	return xxx_messageInfo_RecordResponse.Size(m)
}
func (m *RecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RecordResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("indeed.actuary.v1alpha.LineItemType", LineItemType_name, LineItemType_value)
	proto.RegisterType((*LineItem)(nil), "indeed.actuary.v1alpha.LineItem")
	proto.RegisterMapType((map[string]uint64)(nil), "indeed.actuary.v1alpha.LineItem.DetailEntry")
	proto.RegisterMapType((map[string]string)(nil), "indeed.actuary.v1alpha.LineItem.LabelsEntry")
	proto.RegisterType((*Allocation)(nil), "indeed.actuary.v1alpha.Allocation")
	proto.RegisterMapType((map[string]uint64)(nil), "indeed.actuary.v1alpha.Allocation.DetailEntry")
	proto.RegisterMapType((map[string]string)(nil), "indeed.actuary.v1alpha.Allocation.LabelsEntry")
	proto.RegisterType((*RecordRequest)(nil), "indeed.actuary.v1alpha.RecordRequest")
	proto.RegisterMapType((map[string]uint64)(nil), "indeed.actuary.v1alpha.RecordRequest.AvailableEntry")
	proto.RegisterType((*RecordResponse)(nil), "indeed.actuary.v1alpha.RecordResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 520 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x93, 0x51, 0x8b, 0xd3, 0x40,
	0x14, 0x85, 0x4d, 0x9b, 0x76, 0x9b, 0x5b, 0xad, 0x61, 0x10, 0x09, 0x79, 0xb1, 0x14, 0x57, 0x8a,
	0xc8, 0x2c, 0x56, 0x59, 0x56, 0xf1, 0xa5, 0xbb, 0x69, 0xa1, 0xb0, 0x88, 0xcc, 0x56, 0x04, 0xdf,
	0xa6, 0xed, 0xb5, 0x0d, 0xa6, 0x99, 0x98, 0x4c, 0xba, 0xe4, 0x6f, 0xfa, 0x27, 0x7c, 0xf5, 0x27,
	0xc8, 0xcc, 0x34, 0x6d, 0x17, 0xb6, 0xb4, 0xfa, 0xe4, 0xdb, 0x9d, 0x70, 0xce, 0x37, 0xe7, 0x9e,
	0x30, 0xe0, 0xf0, 0x24, 0xa4, 0x49, 0x2a, 0xa4, 0x20, 0x4f, 0xc3, 0x78, 0x86, 0x38, 0xa3, 0x7c,
	0x2a, 0x73, 0x9e, 0x16, 0x74, 0xf5, 0x9a, 0x47, 0xc9, 0x82, 0xfb, 0xcf, 0xe6, 0x42, 0xcc, 0x23,
	0x3c, 0xd3, 0xaa, 0x49, 0xfe, 0xed, 0x4c, 0x86, 0x4b, 0xcc, 0x24, 0x5f, 0x26, 0xc6, 0xd8, 0xf9,
	0x59, 0x85, 0xc6, 0x75, 0x18, 0xe3, 0x48, 0xe2, 0x92, 0x9c, 0x43, 0x63, 0xc6, 0x25, 0x2a, 0x8d,
	0x67, 0xb5, 0xad, 0x6e, 0xb3, 0xe7, 0x53, 0x03, 0xa0, 0x25, 0x80, 0x8e, 0x4b, 0x00, 0xdb, 0x68,
	0xc9, 0x13, 0xa8, 0x25, 0xbc, 0xc0, 0xd4, 0xab, 0xb4, 0xad, 0xae, 0xc3, 0xcc, 0xa1, 0xfc, 0x8a,
	0x5e, 0x75, 0xfb, 0x15, 0xc9, 0x05, 0xd8, 0xb2, 0x48, 0xd0, 0xb3, 0xdb, 0x56, 0xb7, 0xd5, 0x7b,
	0x4e, 0xef, 0x0f, 0x4e, 0xcb, 0x4c, 0xe3, 0x22, 0x41, 0xa6, 0x1d, 0x8a, 0x97, 0x67, 0x7c, 0x8e,
	0x5e, 0xad, 0x6d, 0x75, 0x6d, 0x66, 0x0e, 0xc4, 0x85, 0x6a, 0x9e, 0xc6, 0x5e, 0x5d, 0xdf, 0xa1,
	0x46, 0x12, 0x40, 0x7d, 0x86, 0x92, 0x87, 0x91, 0x77, 0xd2, 0xae, 0x76, 0x9b, 0xbd, 0x57, 0x87,
	0xee, 0xa0, 0x81, 0x96, 0x0f, 0x62, 0x99, 0x16, 0x6c, 0xed, 0x55, 0x94, 0x88, 0x4f, 0x30, 0xca,
	0xbc, 0xc6, 0x91, 0x94, 0x6b, 0x2d, 0x5f, 0x53, 0x8c, 0xd7, 0x7f, 0x07, 0xcd, 0x1d, 0xb8, 0x0a,
	0xfb, 0x1d, 0x0b, 0xdd, 0xad, 0xc3, 0xd4, 0xa8, 0x96, 0x5a, 0xf1, 0x28, 0x47, 0x5d, 0x9d, 0xcd,
	0xcc, 0xe1, 0x7d, 0xe5, 0xc2, 0x52, 0xd6, 0x1d, 0xe2, 0x21, 0xab, 0xb3, 0x63, 0xed, 0xfc, 0xae,
	0x00, 0xf4, 0xa3, 0x48, 0x4c, 0xb9, 0x0c, 0x45, 0xfc, 0xcf, 0xbf, 0xd5, 0x85, 0xea, 0xed, 0x42,
	0xac, 0xf1, 0x6a, 0x24, 0x04, 0xec, 0xdb, 0x05, 0x97, 0xeb, 0x3f, 0xaa, 0x67, 0x32, 0xdc, 0xd4,
	0x6d, 0xeb, 0xa2, 0xe8, 0xbe, 0xa2, 0xb6, 0x89, 0xee, 0x2d, 0x7c, 0xb8, 0x29, 0xbc, 0x76, 0x34,
	0xe7, 0xff, 0xa9, 0xfc, 0x97, 0x05, 0x8f, 0x18, 0x4e, 0x45, 0x3a, 0x63, 0xf8, 0x23, 0xc7, 0x4c,
	0x12, 0x06, 0x0e, 0x5f, 0xf1, 0x30, 0xe2, 0x93, 0x48, 0xd5, 0xae, 0x56, 0x7a, 0xbb, 0x6f, 0xa5,
	0x3b, 0x4e, 0xda, 0x2f, 0x6d, 0x66, 0xb1, 0x2d, 0x86, 0x04, 0xd0, 0xe4, 0x9b, 0xed, 0x33, 0xaf,
	0xa2, 0xa9, 0x9d, 0xc3, 0x45, 0xb1, 0x5d, 0x9b, 0xff, 0x01, 0x5a, 0x77, 0xaf, 0xf8, 0x9b, 0x92,
	0x3a, 0x2e, 0xb4, 0xca, 0xb8, 0x59, 0x22, 0xe2, 0x0c, 0x5f, 0x9e, 0xc3, 0xc3, 0xdd, 0xe7, 0x4a,
	0x1e, 0x43, 0xf3, 0xf3, 0xc7, 0x9b, 0x4f, 0x83, 0xab, 0xd1, 0x70, 0x34, 0x08, 0xdc, 0x07, 0xc4,
	0x81, 0x5a, 0x30, 0xb8, 0x1c, 0x8d, 0x5d, 0x8b, 0x00, 0xd4, 0xaf, 0xd8, 0x20, 0x18, 0x8d, 0xdd,
	0x4a, 0x2f, 0x84, 0x56, 0xdf, 0x44, 0xbe, 0xc1, 0x74, 0x15, 0x4e, 0x91, 0x7c, 0x81, 0xba, 0x61,
	0x93, 0xd3, 0xa3, 0xaa, 0xf2, 0x5f, 0x1c, 0x92, 0x99, 0x88, 0x97, 0xa7, 0xe0, 0x4f, 0xc5, 0x72,
	0x8f, 0xf8, 0xeb, 0xc9, 0x7a, 0x98, 0xd4, 0xf5, 0x7b, 0x78, 0xf3, 0x27, 0x00, 0x00, 0xff, 0xff,
	0xe2, 0xf5, 0xc4, 0x5d, 0x5a, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ActuaryServiceClient is the client API for ActuaryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ActuaryServiceClient interface {
	Record(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*RecordResponse, error)
}

type actuaryServiceClient struct {
	cc *grpc.ClientConn
}

func NewActuaryServiceClient(cc *grpc.ClientConn) ActuaryServiceClient {
	return &actuaryServiceClient{cc}
}

func (c *actuaryServiceClient) Record(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*RecordResponse, error) {
	out := new(RecordResponse)
	err := c.cc.Invoke(ctx, "/indeed.actuary.v1alpha.ActuaryService/Record", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActuaryServiceServer is the server API for ActuaryService service.
type ActuaryServiceServer interface {
	Record(context.Context, *RecordRequest) (*RecordResponse, error)
}

// UnimplementedActuaryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedActuaryServiceServer struct {
}

func (*UnimplementedActuaryServiceServer) Record(ctx context.Context, req *RecordRequest) (*RecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Record not implemented")
}

func RegisterActuaryServiceServer(s *grpc.Server, srv ActuaryServiceServer) {
	s.RegisterService(&_ActuaryService_serviceDesc, srv)
}

func _ActuaryService_Record_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActuaryServiceServer).Record(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/indeed.actuary.v1alpha.ActuaryService/Record",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActuaryServiceServer).Record(ctx, req.(*RecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ActuaryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "indeed.actuary.v1alpha.ActuaryService",
	HandlerType: (*ActuaryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Record",
			Handler:    _ActuaryService_Record_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
